/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service status */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/methodology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The active methodology version and thresholds
         * @description Returns the active methodology version together with every threshold value
         *     used to evaluate the flags. These thresholds are chosen, not calibrated
         *     against a set of incidents. Consumers are encouraged to apply their own
         *     thresholds by reading the individual flags.
         */
        get: operations["getMethodology"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the monitored assets */
        get: operations["listAssets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/asset/{assetId}/depth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current risk metrics, or metrics at a historical ledger
         * @description Without the `ledger` parameter, this returns the most recent scan from
         *     Horizon. With the `ledger` parameter, it returns a historical replay from
         *     Hubble.
         *
         *     The historical path is batch based and does not guarantee availability for
         *     an arbitrary ledger. If the requested ledger is not available yet, the
         *     response is a 404 with code `LEDGER_NOT_AVAILABLE`, not a 500.
         */
        get: operations["getAssetDepth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/asset/{assetId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A time series of metrics over a ledger range
         * @description Used by the dashboard for trend curves and by the Blend case study page.
         *
         *     TWO QUESTIONS, AND THE PARAMETERS SAY WHICH ONE IS ASKED. With `from` and
         *     `to` this answers "what happened between these two ledgers", capped at 90
         *     days per request, and the points are downsampled into `resolution`
         *     buckets. With BOTH omitted it answers "which readings do you hold for
         *     this source", returns them all without bucketing, and reports the range
         *     that came back in `from` and `to`. One bound without the other is 400
         *     INVALID_RANGE, because it is neither question.
         *
         *     THE SECOND FORM IS THE ONLY WAY TO REACH A RECONSTRUCTION. Stored
         *     `offers-implied` rows sit where the replay ran, which today is February
         *     2026, about 3.2 million ledgers behind the tip. No window inside the 90
         *     day cap contains them, so every windowed request for that source comes
         *     back empty and says nothing about whether anything is stored.
         *
         *     ONE SERIES IS ONE DATA SOURCE. A result is keyed by asset, ledger,
         *     methodology version and data source, so a single ledger can hold several
         *     results that are not comparable with each other: `horizon` and `hubble`
         *     are direct readings, while `offers-implied` and `trades-implied` are
         *     reconstructions, and `trades-implied` proves only liquidity that was
         *     CONSUMED and is therefore a lower bound. This endpoint returns exactly one
         *     source per response and names it in `dataSource`. It defaults to
         *     `horizon`; ask for another by name with `source`.
         */
        get: operations["getAssetHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description A high precision decimal value as a string. DO NOT parseFloat. Use a
         *     decimal library for any arithmetic.
         * @example 124533.4821900
         */
        Decimal: string;
        /**
         * @description The asset type per the Stellar XDR, sent explicitly by Keel.
         *
         *     Consumers MUST NOT infer the type from the length of `code`. A code of
         *     four characters or fewer can be issued as `credit_alphanum12`, and Horizon
         *     reports it as issued. Guessing from code length produces an asset identity
         *     different from the asset that was actually measured.
         * @example credit_alphanum4
         * @enum {string}
         */
        AssetType: "native" | "credit_alphanum4" | "credit_alphanum12";
        Asset: {
            /** @example USDC */
            code: string;
            type: components["schemas"]["AssetType"];
            /**
             * @description Null if and only if `type` is `native`. For both credit types the
             *     issuer is always present.
             * @example GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN
             */
            issuer: string | null;
        };
        /**
         * @description The origin of the data used to compute this response.
         *
         *     `horizon` a live scan of the current orderbook and pools.
         *     `hubble` a replay of historical state from a snapshot.
         *     `offers-implied` the orderbook state at that ledger was unavailable, so the
         *     book was reconstructed by folding two event streams forward to it: the offer
         *     operations (`manage_sell_offer`, `manage_buy_offer` and
         *     `create_passive_sell_offer`) and the trades that consumed them. This is a
         *     reconstruction and it carries `warnings`, but it is a STRONGER source than
         *     `trades-implied`, because an offer proves liquidity that was POSTED.
         *
         *     An offer can also leave the book WITHOUT emitting either kind of event, and
         *     the fold cannot see that on its own. Where this repository has proven a
         *     specific offer absent, the removal is declared in
         *     `configs/known-removals.json` and a run may be told of it by hand; DEC-021
         *     records the case that established this, and
         *     `docs/methodology/01-data-sources.md` section 1.4 carries the rule. The
         *     correction is opt in per run and can only remove depth, never add it. This
         *     field does not say whether a given result used one, and it is not being
         *     widened to: the provenance sidecar beside the artefact names the removals
         *     file and lists every declared removal.
         *
         *     `trades-implied` the orderbook state was unavailable and no offer history
         *     was usable either, so price and liquidity were reconstructed from trades
         *     that actually executed. Every depth figure it produces is a lower bound
         *     rather than a measurement: a trade proves only the liquidity that was
         *     CONSUMED, not the liquidity that was available. Do not display a
         *     `trades-implied` result as equivalent to a `horizon` result.
         *
         *     Confidence order, highest first: `horizon` and `hubble` are read directly,
         *     then `offers-implied`, then `trades-implied`.
         *
         *     Known limitation of this field: it squashes two different questions into one
         *     enum, where the data came from and how it was reconstructed. The accurate
         *     shape is two fields, a source and a derivation, and that is deferred rather
         *     than forgotten.
         * @enum {string}
         */
        DataSource: "horizon" | "hubble" | "offers-implied" | "trades-implied";
        /**
         * @description A risk condition that fired. Flags are reported individually so that a
         *     consumer can apply their own policy rather than depending only on the band.
         * @enum {string}
         */
        Flag: "NO_EXECUTABLE_PRICE" | "ZERO_DEPTH_2PCT" | "MANIPULATION_CHEAP" | "MANIPULATION_RATIO_LOW" | "NO_GENUINE_TRADE_30D" | "NO_GENUINE_TRADE_7D" | "HOLDER_CONCENTRATION_EXTREME" | "HOLDER_CONCENTRATION_HIGH" | "THIN_DEPTH_5PCT" | "WASH_TRADE_SUSPECTED" | "SPREAD_EXTREME" | "PRICE_SOURCE_CONFLICT";
        /**
         * @description The worst flag level that fired. Not the result of a weighting.
         * @enum {string}
         */
        Band: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        /**
         * @description Whether the band rests on a complete check.
         *
         *     `full` every flag at the CRITICAL and HIGH levels could be evaluated.
         *     `partial` at least one flag at those levels could not be evaluated at all,
         *     so the band is a floor rather than a verdict. It can only be worse than
         *     reported, never better.
         * @enum {string}
         */
        BandConfidence: "full" | "partial";
        DepthPoint: {
            /**
             * @description The relative price shift; 0.02 means 2 percent
             * @enum {number}
             */
            delta: 0.02 | 0.05 | 0.1;
            /**
             * @description The notional in the quote asset that can be absorbed by buying before
             *     the marginal price passes P0 times (1 + delta). Relevant to oracle
             *     manipulation risk.
             */
            buySide: components["schemas"]["Decimal"];
            /**
             * @description The notional in the quote asset that can be absorbed by selling before
             *     the marginal price falls below P0 times (1 - delta). Relevant to
             *     liquidation risk.
             */
            sellSide: components["schemas"]["Decimal"];
            /** @description The SDEX orderbook contribution on the buy side, for transparency */
            fromSdex: components["schemas"]["Decimal"];
            /** @description The AMM pool contribution on the buy side, for transparency */
            fromAmm: components["schemas"]["Decimal"];
        };
        /**
         * @description One rung of the upward price manipulation simulation. The full ladder is
         *     0.5, 1, 10, and 100. The large rungs are included deliberately, because an
         *     asset with a broken book is invisible to the small ones.
         */
        ManipulationCost: {
            /**
             * @description The simulated relative price increase. 0.5 means a rise of 50 percent,
             *     100 means a rise of 10000 percent.
             * @enum {number}
             */
            delta: 0.5 | 1 | 10 | 100;
            /**
             * @description The simulated target price, that is `midPrice` times (1 + delta). It is
             *     sent so that consumers do not have to recompute it and so that the
             *     ladder stays readable when `midPrice` itself makes no sense.
             */
            targetPrice: components["schemas"]["Decimal"];
            /**
             * @description The notional in the quote asset required to absorb every ask below
             *     `targetPrice`. MUST be read together with `reachable`.
             */
            cost: components["schemas"]["Decimal"];
            /**
             * @description True when `targetPrice` really can be attained by absorbing liquidity
             *     step by step. False when liquidity runs out before `targetPrice` is
             *     reached, so the price can only jump to the nearest available ask rather
             *     than being walked to the target.
             *
             *     The combinations that must be displayed differently:
             *
             *     | cost | reachable | meaning |
             *     |---|---|---|
             *     | 0 | true | the target price is attainable at no cost |
             *     | 0 | false | there is no liquidity at all in that range |
             *     | > 0 | true | a real cost to reach the target |
             *     | > 0 | false | the cost exhausts every ask and still does not reach the target |
             *
             *     THE TABLE ABOVE APPLIES TO `manipulationCostOrderbookOnly` ONLY. On
             *     `manipulationCostCombined` this field is unconditionally `true`
             *     whenever an active pool is present on the pair, because a constant
             *     product curve has no upper price bound: the marginal price grows
             *     without limit as the base reserve is drained, so no target is out of
             *     reach. A `true` there is a property of the curve and not a
             *     measurement of this asset, and none of the four rows above can be
             *     distinguished on that ladder.
             *
             *     Consumers deciding whether a target is attainable MUST read
             *     `manipulationCostOrderbookOnly`. That is the ladder Keel itself uses:
             *     `maxSafeCollateralManipulation` and `oracleResistance.reachable` both
             *     take their value from it, because an attacker takes the cheapest path
             *     and orderbook-only is never above combined.
             *
             *     This is the same presence rule as `maxReachablePrice`, pointing the
             *     other way. Presence of an active pool removes the upper bound, which
             *     makes a highest price meaningless there and makes every target
             *     reachable here.
             *
             *     See also `maxReachablePrice`.
             */
            reachable: boolean;
        };
        /**
         * @description The asset's resistance to oracle price manipulation. It answers one
         *     question: is moving the price to a critical level cheaper than the genuine
         *     trading volume that actually occurred during the window the oracle uses.
         *
         *     A manipulation cost on its own is not enough. A cost of 10000 XLM is cheap
         *     for an asset trading 5 million XLM a day, and expensive for an asset
         *     trading 200 XLM a day. It is that comparison that is reported here, not
         *     the raw cost alone.
         */
        OracleResistance: {
            /**
             * @description The delta treated as the critical threshold for this asset. Equal to
             *     one of the `delta` values in `manipulationCostOrderbookOnly`.
             * @example 0.5
             */
            criticalDelta: number;
            /**
             * @description The `cost` of the `manipulationCostOrderbookOnly` entry at
             *     `criticalDelta`, copied here so consumers do not have to match it up
             *     themselves. The orderbook-only variant, because an attacker takes the
             *     cheapest path.
             */
            manipulationCost: components["schemas"]["Decimal"];
            /**
             * @description The `reachable` value of the same entry. When false, the
             *     `manipulationCost` above does not state the cost of reaching the
             *     target, and both `ratio` and `totalAttackCost` are null.
             */
            reachable: boolean;
            /**
             * @description The genuine trade volume in the quote asset over the last
             *     `windowSeconds`, after the genuine trade filtering rules are applied.
             *     This is the comparison baseline for the manipulation cost.
             */
            genuineVolume: components["schemas"]["Decimal"];
            /**
             * @description The length of the observation window in seconds, equal to
             *     `oracleWindowSeconds` at GET /methodology. It is repeated here so that
             *     the response can be read without calling another endpoint.
             * @example 900
             */
            windowSeconds: number;
            /**
             * @description `manipulationCost` divided by `genuineVolume`. A value below 1 means
             *     that moving the price to the critical level is cheaper than all of the
             *     genuine trading across the oracle window. Null when `genuineVolume` is
             *     zero or `reachable` is false, because the division is then meaningless.
             */
            ratio?: components["schemas"]["Decimal"] | null;
            /**
             * @description `manipulationCost` PLUS `genuineVolume`, added in methodology 1.0.3.
             *
             *     It answers a different question from `ratio`. The ratio asks whether the
             *     attack is cheap relative to the market it has to hide inside, and being
             *     dimensionless it can rank many assets against each other. This asks how
             *     much capital an attack on an averaging oracle needs in TOTAL, because
             *     the attacker has to pay the book and also outweigh the genuine volume
             *     inside the window. Being in the quote asset, it can only be read against
             *     one pair.
             *
             *     It is a LOWER BOUND. Needing exactly `genuineVolume` of extra volume to
             *     dominate a volume weighted average is an approximation; what is really
             *     required depends on the weighting and on where in the window the attack
             *     lands.
             *
             *     Null when `reachable` is false, for the same reason `ratio` is.
             */
            totalAttackCost?: components["schemas"]["Decimal"] | null;
        };
        /**
         * @description One phrase per supporting figure saying why it is null. A key is null
         *     when its figure is present or no reason was recorded, so a consumer reads
         *     a note only beside a null figure. The phrases are prose for a reader and
         *     not an enum: do not branch on their text.
         *
         *     They keep apart the absences a bare null collapses. A trustline set too
         *     large for the holder pull, a pair above the trade threshold, a walk that
         *     spent its page bound, and a search that covered thirty whole days and
         *     found no genuine trade are four different answers, and only the last is
         *     a measurement.
         */
        SupportingNotes: {
            /** @description Why holderTop1Pct, holderTop10Pct and holderHhi are null. They come from one trustline pull and are absent together. */
            holders: string | null;
            tradesExcludedPct: string | null;
            /** @description Why volumeToSupply is null, or, when it is present, why its d30 window is. */
            volumeToSupply: string | null;
            /**
             * @description Why lastGenuineTrade is null. A note that begins "not checked" means
             *     the search stopped before it could answer, and is not evidence that
             *     the asset has no genuine trade.
             */
            lastGenuineTrade: string | null;
        };
        VolumeToSupply: {
            d1: components["schemas"]["Decimal"];
            d7: components["schemas"]["Decimal"];
            d30: components["schemas"]["Decimal"];
        };
        LastGenuineTrade: {
            /** Format: int64 */
            ledgerSeq: number;
            /** Format: date-time */
            at: string;
        };
        /**
         * @description One evaluated quote pair, reduced to the fields that are COMPARABLE ACROSS
         *     PAIRS. Depth, manipulation cost and collateral are deliberately absent: each
         *     is denominated in its own pair's quote asset, and two units side by side in
         *     one response invite arithmetic that mixes them. A band and a confidence are
         *     unitless.
         */
        PairSummary: {
            quote: components["schemas"]["Asset"];
            band: components["schemas"]["Band"];
            bandConfidence: components["schemas"]["BandConfidence"];
        };
        AssetRisk: {
            asset: components["schemas"]["Asset"];
            /** @description The unit of every notional value in this response */
            quote: components["schemas"]["Asset"];
            /**
             * @description The quote asset every headline figure in this response is denominated
             *     in. It is USDC for every asset and is not chosen per asset, so it is
             *     redundant with `quote` today. It is sent anyway, because widening the
             *     candidate quote set later must not silently change what an
             *     already-stored row meant.
             *
             *     **OPTIONAL in 1.5.0 and absent from every example.** The field is
             *     declared here so a consumer can be built against it; nothing populates
             *     it until the multi-pair evaluation lands. Do not assume presence.
             */
            primaryQuote?: components["schemas"]["Asset"];
            /**
             * @description Every quote pair evaluated for this asset, the primary one included,
             *     sorted by quote asset so the order is reproducible. In this version the
             *     candidate set is exactly two members, USDC and native XLM, which is a
             *     stated bound on FR-11 rather than an unstated shortfall.
             *
             *     This array exists so the cheapest-path finding survives the scope cut in
             *     PRD section 12: `?quote=` is priority C and goes first, and three fields
             *     per pair in the primary response do not.
             *
             *     **OPTIONAL in 1.5.0 and absent from every example**, for the reason on
             *     `primaryQuote`.
             */
            pairsEvaluated?: components["schemas"]["PairSummary"][];
            /**
             * @description The quote asset of the pair whose evaluation set `band`. `band` is the
             *     highest tier triggered on ANY evaluated pair, because an attacker takes
             *     the cheapest path: an asset deep against USDC and thin against XLM is not
             *     a safe asset.
             *
             *     **This is the field that makes a mixed display detectable.** When it is
             *     not equal to `primaryQuote`, the warning `SECONDARY_PAIR_WORSE` is in
             *     `warnings`, and `band` then describes a different market from the
             *     `depth`, `manipulationCost*` and `maxSafeCollateral` beside it, which
             *     always stay the primary pair's figures. A dashboard must not present the
             *     two as one reading in that case.
             *
             *     **OPTIONAL in 1.5.0 and absent from every example**, for the reason on
             *     `primaryQuote`.
             */
            bandDrivenBy?: components["schemas"]["Asset"];
            /**
             * @description The XLM/USDC mid price at this `ledgerSeq`. Published because the
             *     absolute thresholds are USDC figures, so an XLM-quoted pair is converted
             *     before it is judged against them, and a reader has to be able to redo
             *     that conversion with a rate of their own.
             *
             *     Not a price oracle: it is read from the same books and pools as
             *     everything else in this response, from the deepest market on the network,
             *     at the same ledger.
             *
             *     Null when no XLM-quoted pair was evaluated, and null when the rate was not
             *     trustworthy at that ledger. The two are not distinguished by value; the
             *     second case shows up in `pairsEvaluated` as an XLM entry with
             *     `bandConfidence: partial`.
             *
             *     **OPTIONAL in 1.5.0 and absent from every example**, for the reason on
             *     `primaryQuote`.
             */
            xlmUsdcRate?: components["schemas"]["Decimal"] | null;
            /** Format: int64 */
            ledgerSeq: number;
            /** Format: date-time */
            ledgerClosedAt: string;
            /** Format: date-time */
            computedAt: string;
            methodologyVersion: string;
            dataSource: components["schemas"]["DataSource"];
            /**
             * @description Null when priceSource is none. Note that a populated midPrice is not
             *     necessarily meaningful: when `SPREAD_EXTREME` fires, this number is the
             *     midpoint of two prices that have nothing to do with each other.
             */
            midPrice?: components["schemas"]["Decimal"] | null;
            /**
             * @description `book` means the orderbook mid, `pool` means the pool spot price,
             *     `none` means the asset has no executable price at all. The value `none`
             *     is not an error.
             *
             *     Changed in methodology 1.0.3. `pool` no longer means only that the book
             *     was empty or one sided. When both a book and a pool exist and they
             *     disagree by more than `priceDivergencePct`, the pool wins, because it is
             *     backed by executable liquidity in both directions, and
             *     `PRICE_SOURCE_CONFLICT` fires. Read `poolSpotPrice` and
             *     `priceDivergencePct` to see the disagreement rather than only its
             *     outcome.
             * @enum {string}
             */
            priceSource: "book" | "pool" | "none";
            /**
             * @description The difference between the best ask and the best bid divided by
             *     `midPrice`, expressed in PERCENT, following the convention of every
             *     field in this API whose name ends in `Pct`. A value of '196.0777141'
             *     means a spread of 196 percent.
             *
             *     Null when either side of the book is empty or when `priceSource` is not
             *     `book`, because a spread is undefined without two sides of a book.
             *
             *     A value above `spreadExtremePct` triggers `SPREAD_EXTREME`. Above that
             *     threshold, `midPrice` and every metric derived from it, including the
             *     2/5/10 percent depth ladder, lose their meaning.
             */
            spreadPct: components["schemas"]["Decimal"] | null;
            /**
             * @description The marginal price of the AMM pool with the largest quote reserve,
             *     reported whenever an active pool exists, whichever source `priceSource`
             *     ended up naming. A consumer comparing two price sources needs both
             *     numbers and not only the one that won.
             *
             *     Null when there is no active pool.
             */
            poolSpotPrice?: components["schemas"]["Decimal"] | null;
            /**
             * @description The distance between the orderbook mid and `poolSpotPrice`, in PERCENT.
             *     Above `priceDivergencePct` at GET /methodology, `priceSource` becomes
             *     `pool` and `PRICE_SOURCE_CONFLICT` fires.
             *
             *     Null when there is no active pool. Null means undefined here and not
             *     zero: an asset with no pool has no divergence, while a zero would claim
             *     the two sources agree.
             */
            priceDivergencePct?: components["schemas"]["Decimal"] | null;
            depth: components["schemas"]["DepthPoint"][];
            /**
             * @description The 0.5, 1, 10, 100 ladder in ascending delta order, counting BOTH the
             *     orderbook and every active AMM pool. An empty array when there is no
             *     executable price.
             *
             *     RENAMED in contract 1.3.0, from `manipulationCost`. Methodology 1.0.3
             *     split this metric in two because they answer different questions, and a
             *     single name could only have meant one of them.
             */
            manipulationCostCombined: components["schemas"]["ManipulationCost"][];
            /**
             * @description The same ladder counting the ORDERBOOK ONLY.
             *
             *     `manipulationCostOrderbookOnly[i].cost` is always less than or equal to
             *     `manipulationCostCombined[i].cost`, because combined is the same book
             *     plus an AMM term. An attacker takes the cheapest path, so this is the
             *     binding figure and it is the one used in `maxSafeCollateral`.
             *
             *     **The gap between the two is itself the signal.** An asset with a large
             *     combined cost and a small orderbook-only cost looks defended and is not,
             *     and that is exactly what happened on 22 February 2026: an honest pool
             *     held the price at 1.0555 throughout, moving the real market price to
             *     106.74 would have cost about 147.96 USDC, and the attacker paid zero by
             *     using the orderbook alone. A display that shows only one of these two
             *     numbers should show this one.
             *
             *     That an oracle reads only SDEX trades is an INFERENCE from that
             *     incident, not a confirmed fact about any oracle.
             */
            manipulationCostOrderbookOnly: components["schemas"]["ManipulationCost"][];
            /**
             * @description What reaching `maxReachablePrice` costs, meaning the sum of every ask
             *     notional strictly below it.
             *
             *     Read this together with `maxReachablePrice` and not on its own. The
             *     pair is what catches an attack that lands between two rungs of the
             *     manipulation ladder, and on the USTRY fixture it is the only thing
             *     that caught the real one: the highest reachable price was 106.7372828
             *     and reaching it cost zero.
             *
             *     Note the shape of the definition. Because the sum is over asks
             *     strictly below the maximum, a book whose only ask IS the maximum
             *     yields zero here by construction, for any asset. A zero is therefore
             *     a statement about the shape of the book, not a discovery about the
             *     asset, and a display should say how many ask levels exist beside it.
             *
             *     Null in the same two situations as `maxReachablePrice`.
             */
            costToMaxReachablePrice: components["schemas"]["Decimal"] | null;
            /**
             * @description The highest price still attainable by absorbing every available ask.
             *     This is the real upper bound on price movement through the orderbook.
             *
             *     Every `manipulationCostOrderbookOnly` entry whose `targetPrice` sits above this
             *     value is necessarily `reachable: false`.
             *
             *     Null in two situations: there is no ask at all on this pair, or an
             *     active pool is present on it. Both fields are meaningful only for a
             *     pure orderbook market. Under a constant product curve the price tends
             *     to infinity as the base reserve tends to zero, so every target is
             *     reachable and a highest price has no meaning.
             *
             *     THE RULE IS PRESENCE, NOT EXCLUSIVITY, and the difference is the
             *     whole of it. A pair carrying BOTH a book and an active pool reports
             *     null here, not the book's highest ask. Until contract 1.4.3 this
             *     description keyed the null on the pool being the sole source of
             *     liquidity, which gives the opposite answer on exactly that market,
             *     and the AssetHealthy example below was built on the old reading.
             *     `docs/methodology/05-manipulation-cost.md` section 5 is the binding
             *     definition and `internal/domain.maxReachable` already implemented it;
             *     this description was the only place that disagreed.
             */
            maxReachablePrice: components["schemas"]["Decimal"] | null;
            /**
             * @description Null in two cases, and `warnings` names which. When there is no
             *     executable price, because then there is no price to move. And when the
             *     genuine volume inside the oracle window was not measured at THIS row's
             *     ledger: the object pairs a manipulation cost at this ledger with the
             *     volume in the `windowSeconds` before it, and a volume from another
             *     instant would make that pairing meaningless. A reconstructed historical
             *     row carries no trade history and is null for the second reason.
             */
            oracleResistance?: components["schemas"]["OracleResistance"] | null;
            /**
             * @description The recommended maximum collateral size in the quote asset, the MINIMUM
             *     of the two terms below. Null when it cannot be computed, for example
             *     because there is no executable price.
             */
            maxSafeCollateral?: components["schemas"]["Decimal"] | null;
            /**
             * @description The liquidation term, `depth.sellSide` at the liquidation delta times
             *     the haircut. Always present when `maxSafeCollateral` is.
             *
             *     Reported separately because the minimum alone hides WHICH limit binds,
             *     and that is the part a lender acts on. A position limited by liquidation
             *     depth and one limited by manipulation cost call for different responses.
             */
            maxSafeCollateralLiquidation?: components["schemas"]["Decimal"] | null;
            /**
             * @description The manipulation term, `manipulationCostOrderbookOnly` at the critical
             *     delta times the safety margin.
             *
             *     Null when the critical target is UNREACHABLE through the orderbook. The
             *     term is then not applied at all, `maxSafeCollateral` falls back to the
             *     liquidation term alone, and a `warnings` entry says so. Null here means
             *     not applicable, and it is not zero: zero would claim the attack is free.
             */
            maxSafeCollateralManipulation?: components["schemas"]["Decimal"] | null;
            holderTop1Pct?: components["schemas"]["Decimal"] | null;
            holderTop10Pct?: components["schemas"]["Decimal"] | null;
            holderHhi?: components["schemas"]["Decimal"] | null;
            volumeToSupply?: components["schemas"]["VolumeToSupply"] | null;
            /** @description Null when no genuine trade was found at all */
            lastGenuineTrade?: components["schemas"]["LastGenuineTrade"] | null;
            /**
             * @description The percentage of 30 day volume excluded by the genuine trade rules. A
             *     high value indicates suspected wash trading.
             */
            tradesExcludedPct?: components["schemas"]["Decimal"] | null;
            /**
             * @description Why each absent supporting figure above is absent. Added in 1.9.0.
             *
             *     Null when there is nothing to explain: every supporting figure is
             *     present, or the row was stored before the engine recorded reasons, or
             *     the row is a reconstruction, whose reasons travel in `warnings`.
             */
            supportingNotes?: components["schemas"]["SupportingNotes"] | null;
            /** @description The flags that are `triggered`. */
            flags: components["schemas"]["Flag"][];
            /**
             * @description The flags that could NOT be checked, because the data they need is
             *     absent from this response's inputs.
             *
             *     `unevaluated` is not a synonym for `clear`. A flag missing from both
             *     `flags` and `unevaluatedFlags` was checked and found not to apply. A
             *     flag listed here was never checked at all, and an asset with no
             *     trustline data must not be displayed as though its holder distribution
             *     had been examined and found safe.
             */
            unevaluatedFlags: components["schemas"]["Flag"][];
            band: components["schemas"]["Band"];
            /**
             * @description Whether the band rests on a complete check. **The dashboard is
             *     required to display this.** A `LOW` band with `partial` confidence is a
             *     far weaker statement than `LOW` with `full`, and hiding the difference
             *     makes an unchecked asset look safe.
             */
            bandConfidence: components["schemas"]["BandConfidence"];
            /**
             * @description Notes about the limitations of the computation behind this response.
             *     These should be shown to the user, not hidden.
             */
            warnings: string[];
            reconstruction?: components["schemas"]["Reconstruction"];
        };
        /**
         * @description What the acquisition of a RECONSTRUCTED book detected about its own
         *     completeness. Added in 1.7.0 by DEC-022.
         *
         *     **ABSENT MEANS THIS ROW IS NOT A RECONSTRUCTION. It never means a walk ran
         *     and found nothing.** A `horizon` response reads the live book directly and
         *     walks nothing, so it has no gaps to report and this key is omitted rather
         *     than sent as null. A consumer that renders "gaps: unknown" beside a direct
         *     reading has read the absence backwards.
         *
         *     **EVERY COUNTER IN HERE REMOVES OFFERS, so a row carrying them describes a
         *     book that is too THIN and never too deep.** Read its depth as a lower bound
         *     and its risk as an upper bound. The two gaps that would run the other way,
         *     a book inflated by offers that were already eaten and a crossed book, can
         *     never appear on a stored row: a reconstruction carrying either is refused
         *     before it is computed, with no override.
         *
         *     **It is not a quality score and not a proof.** Zero everywhere means this
         *     walk detected nothing, not that it saw every offer. An offer whose owner
         *     never traded and is not resting today is invisible to this method, which is
         *     the limitation `01-data-sources.md` states and this object cannot see.
         *
         *     `warnings` carries the same facts as sentences. Both are sent on purpose:
         *     this object is for a consumer that branches, the prose is for the reader of
         *     a response who never will.
         */
        Reconstruction: {
            /** @description Account walks that reached their page cap before the account ran out of operations */
            truncated: number;
            /**
             * @description Account walks that ended at the operation floor rather than at the
             *     account's own first operation. Read it with `floorLedger`: an offer
             *     created before that ledger is invisible to this row.
             */
            stoppedAtFloor: number;
            /** @description Account walks that failed at the data source and contributed no offers */
            failed: number;
            /** @description Operation results whose remaining amount could not be read */
            unsizable: number;
            /**
             * @description Offers that a later trade named as resting and that this walk never saw
             *     created. Each one is a hole the reconstruction found in itself.
             */
            missingOffers: number;
            /**
             * Format: int64
             * @description The operation floor the walk was given, or 0 when it was given none.
             *     Present so that `stoppedAtFloor` can be read as a statement about which
             *     offers are missing rather than as a bare count.
             */
            floorLedger: number;
            /**
             * @description The denominator for the three walk counters above. 42 of 65 is a
             *     different statement from 42 of 400.
             */
            accountsWalked: number;
        };
        AssetSummary: {
            asset: components["schemas"]["Asset"];
            quote: components["schemas"]["Asset"];
            midPrice?: components["schemas"]["Decimal"] | null;
            /** @enum {string} */
            priceSource?: "book" | "pool" | "none";
            depth5PctBuySide?: components["schemas"]["Decimal"] | null;
            maxSafeCollateral?: components["schemas"]["Decimal"] | null;
            band: components["schemas"]["Band"];
            /**
             * @description Present on the list row as well as on the detail response, because the
             *     list is where a band is read fastest and with the least context. A row
             *     showing `LOW` with no confidence marker is exactly the misleading
             *     display the methodology forbids.
             */
            bandConfidence: components["schemas"]["BandConfidence"];
            flags: components["schemas"]["Flag"][];
            /** Format: int64 */
            ledgerSeq: number;
        };
        AssetListResponse: {
            items: components["schemas"]["AssetSummary"][];
            total: number;
            limit: number;
            offset: number;
            methodologyVersion: string;
        };
        HistoryPoint: {
            /** Format: int64 */
            ledgerSeq: number;
            /** Format: date-time */
            ledgerClosedAt: string;
            midPrice?: components["schemas"]["Decimal"] | null;
            depth2PctBuySide?: components["schemas"]["Decimal"] | null;
            depth5PctBuySide?: components["schemas"]["Decimal"] | null;
            depth10PctBuySide?: components["schemas"]["Decimal"] | null;
            manipulationCost50Pct?: components["schemas"]["Decimal"] | null;
            maxSafeCollateral?: components["schemas"]["Decimal"] | null;
            band: components["schemas"]["Band"];
            flags: components["schemas"]["Flag"][];
        };
        HistoryResponse: {
            asset: components["schemas"]["Asset"];
            quote: components["schemas"]["Asset"];
            /** Format: int64 */
            from: number;
            /** Format: int64 */
            to: number;
            /** @enum {string} */
            resolution: "hour" | "day";
            methodologyVersion: string;
            dataSource: components["schemas"]["DataSource"];
            /**
             * @description Ledger ranges inside the request for which no data is available. The
             *     dashboard is required to display these gaps rather than interpolate
             *     across them.
             */
            gaps?: {
                /** Format: int64 */
                from: number;
                /** Format: int64 */
                to: number;
                reason: string;
            }[];
            points: components["schemas"]["HistoryPoint"][];
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /** Format: date-time */
            latestScanAt?: string;
            /** Format: int64 */
            latestScanLedgerSeq?: number;
            assetsMonitored?: number;
            methodologyVersion: string;
            /** @description False when the Hubble path is currently unavailable */
            historicalAvailable?: boolean;
            /** @description The commit this binary was built from, stamped at link time. It is a different question from methodologyVersion beside it: that one names the definitions the numbers follow, this one names the build that produced them, and two deployments can agree on the first while disagreeing on the second. Always present. Reads "unknown" on a build that carried no stamp, which is the honest answer for a local `go build` and a signal worth investigating on a deployed one. */
            buildRevision?: string;
        };
        Methodology: {
            version: string;
            /** Format: uri */
            documentUrl: string;
            /** @description Always false in v1. The thresholds are chosen, not calibrated. */
            calibrated: boolean;
            calibrationNote?: string;
            /**
             * @description A map of named thresholds. It is open ended: new keys can appear
             *     without a major API version bump, so consumers are required to read
             *     them by key name rather than by position.
             *
             *     Unit convention: every key ending in `Pct` is expressed in percent, not
             *     as a fraction. `spreadExtremePct: '20.0'` means 20 percent and is
             *     compared directly against `spreadPct` in an asset response.
             */
            thresholds: {
                /**
                 * @description The threshold that triggers SPREAD_EXTREME, in percent. Above this
                 *     threshold the reference price is considered meaningless and the
                 *     asset enters band HIGH.
                 */
                spreadExtremePct?: components["schemas"]["Decimal"];
                /**
                 * @description How far the orderbook mid may sit from the pool spot price before
                 *     the pool is preferred as the reference price, in percent. Crossing
                 *     it sets `priceSource` to `pool` and fires
                 *     `PRICE_SOURCE_CONFLICT`. Added in methodology 1.0.3.
                 */
                priceDivergencePct?: components["schemas"]["Decimal"];
                /**
                 * @description The assumed length of the window an oracle uses to average prices,
                 *     in seconds. Used as the comparison baseline for genuine volume in
                 *     `oracleResistance`. This threshold is chosen, not read from any
                 *     oracle, because every oracle has its own window.
                 */
                oracleWindowSeconds?: number;
                /**
                 * @description The threshold that triggers MANIPULATION_RATIO_LOW, in percent,
                 *     following the convention above.
                 *
                 *     The rule multiplies the manipulation cost over the circulating
                 *     supply VALUE by 100 before the comparison, so the factor of 100
                 *     belongs to the rule and not to this number: '0.1' means a tenth of
                 *     one percent. Stated explicitly because that is the ambiguity
                 *     DEC-017 was written to settle, and the two readings of it differ
                 *     by a hundredfold. The value moved from 1.0 to 0.1 on 10 September
                 *     2026 by that record.
                 */
                manipulationRatioLowPct?: components["schemas"]["Decimal"];
                /**
                 * @description The downward price move the collateral calculation assumes, as a
                 *     relative shift; 0.1 means 10 percent. This is "the liquidation
                 *     delta" named in `maxSafeCollateralLiquidation`, and it selects
                 *     which rung of the `depth` ladder that term reads.
                 *
                 *     Sent as a NUMBER and not a string. That is the same exception
                 *     point 1 of this API's description makes for `delta`, and for the
                 *     same reason: it is a ladder position, not a monetary value.
                 */
                liquidationDelta?: number;
                /**
                 * @description The share of `depth.sellSide` at `liquidationDelta` that the
                 *     liquidation term is allowed to claim. This is "the haircut" named
                 *     in `maxSafeCollateralLiquidation`.
                 *
                 *     A FRACTION and not a percent: '0.5' means half. The name carries
                 *     no `Pct` suffix for exactly that reason, which is the only signal
                 *     distinguishing it from the keys above it.
                 */
                liquidationHaircut?: components["schemas"]["Decimal"];
                /**
                 * @description The rung of the `manipulationCostOrderbookOnly` ladder that the
                 *     manipulation term of `maxSafeCollateral` reads; 0.5 means 50
                 *     percent. This is "the critical delta" named in
                 *     `maxSafeCollateralManipulation`, and it is where that term's
                 *     `reachable` check is made.
                 *
                 *     It does NOT scope the MANIPULATION_CHEAP flag, which scans every
                 *     reachable rung rather than this one. A number, for the reason given
                 *     on `liquidationDelta`.
                 */
                manipulationCriticalDelta?: number;
                /**
                 * @description The share of the manipulation cost at `manipulationCriticalDelta`
                 *     that the manipulation term is allowed to claim. This is "the safety
                 *     margin" named in `maxSafeCollateralManipulation`. A fraction and not
                 *     a percent, as with `liquidationHaircut`.
                 */
                manipulationMargin?: components["schemas"]["Decimal"];
            } & {
                [key: string]: unknown;
            };
        };
        Error: {
            error: {
                /** @enum {string} */
                code: "INVALID_ASSET_ID" | "INVALID_RANGE" | "ASSET_NOT_MONITORED" | "LEDGER_NOT_AVAILABLE" | "HISTORICAL_UNAVAILABLE" | "RATE_LIMITED";
                /** @description A message that may be shown directly to the user */
                message: string;
                detail?: {
                    [key: string]: unknown;
                };
            };
        };
    };
    responses: {
        /** @description Invalid parameter */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description The asset is not monitored, or the requested ledger is not available. Both
         *     are ordinary conditions, not system failures.
         */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The historical path is currently unavailable. The live path is unaffected. */
        HistoricalUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "HISTORICAL_UNAVAILABLE",
                 *         "message": "The historical data service is currently unavailable. Current metrics remain accessible without the ledger parameter."
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Exceeded 60 requests per minute */
        RateLimited: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "RATE_LIMITED",
                 *         "message": "The limit of 60 requests per minute was exceeded."
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /**
         * @description The asset identity. The format is `CODE:ISSUER` for an issued asset, or
         *     `XLM` for the native asset. The colon does not need encoding, but a
         *     consumer using a strict URL builder may encode it as `%3A`.
         */
        AssetId: string;
        /**
         * @description The quote asset used as the unit of measurement. If omitted, the asset's
         *     PRIMARY pair is used, and the primary pair is always
         *     USDC:GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN. That is
         *     `docs/methodology/02-pair-selection.md` section 2, and it follows from
         *     section 1: the candidate quote set is exactly USDC and native XLM, and
         *     every threshold is a USDC figure.
         *
         *     It is a fixed identity and not a measurement, so the pair this resolves to
         *     does not change when depth changes. Until contract 1.5.1 this parameter
         *     described the primary pair as the one with the largest combined depth at
         *     10 percent; no such rule was ever adopted and DEC-015 replaced it.
         *
         *     An asset measured against several quotes with no USDC pair among them
         *     cannot resolve without this parameter and answers 400 INVALID_ASSET_ID
         *     listing its `quoteCandidates` and the `primaryQuote` it was looking for.
         * @example XLM
         */
        Quote: string;
        /**
         * @description The ledger sequence for a historical replay. When set, `dataSource` in the
         *     response will be `hubble`.
         * @example 60912345
         */
        Ledger: number;
        /** @description Filter by risk band */
        Band: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        /** @description Filter for assets that trigger a specific flag */
        HasFlag: components["schemas"]["Flag"];
        Limit: number;
        Offset: number;
    };
    requestBodies: never;
    headers: {
        /**
         * @description How many seconds behind the latest ledger this data was when it was
         *     computed. For a historical response the value is 0, because historical
         *     data does not go stale.
         * @example 412
         */
        Staleness: number;
        /**
         * @description The methodology version that produced the numbers in this response
         * @example 1.0.0
         */
        MethodologyVersion: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "latestScanAt": "2026-08-19T04:15:00Z",
                     *       "latestScanLedgerSeq": 61234567,
                     *       "assetsMonitored": 53,
                     *       "methodologyVersion": "1.0.8-draft",
                     *       "historicalAvailable": true,
                     *       "buildRevision": "9f8c2a1d4b7e6053c1a2f8d9e0b3c7a6d5e4f312"
                     *     }
                     */
                    "application/json": components["schemas"]["Health"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    getMethodology: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The active methodology */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "version": "1.0.8-draft",
                     *       "documentUrl": "https://github.com/Keel-Official/keel-backend/blob/main/docs/methodology/00-overview.md",
                     *       "calibrated": false,
                     *       "calibrationNote": "The thresholds were chosen based on the magnitude of the Blend incident of February 2026 and on conservative judgement, not calibrated against a set of incidents. Every flag is reported separately so that consumers can apply their own thresholds.",
                     *       "thresholds": {
                     *         "manipulationCheapAbsolute": "10000",
                     *         "manipulationCheapUnit": "USDC:GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN",
                     *         "manipulationRatioLowPct": "0.1",
                     *         "thinDepth5PctAbsolute": "50000",
                     *         "thinDepth5PctUnit": "USDC:GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN",
                     *         "holderTop1ExtremePct": "50",
                     *         "holderTop10HighPct": "80",
                     *         "genuineTradeStaleDays": 30,
                     *         "genuineTradeWarnDays": 7,
                     *         "washTradeSuspectedPct": "50",
                     *         "spreadExtremePct": "20",
                     *         "priceDivergencePct": "10",
                     *         "oracleWindowSeconds": 900,
                     *         "liquidationDelta": 0.1,
                     *         "liquidationHaircut": "0.5",
                     *         "manipulationCriticalDelta": 0.5,
                     *         "manipulationMargin": "0.25"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Methodology"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    listAssets: {
        parameters: {
            query?: {
                /** @description Filter by risk band */
                band?: components["parameters"]["Band"];
                /** @description Filter for assets that trigger a specific flag */
                hasFlag?: components["parameters"]["HasFlag"];
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The asset list */
            200: {
                headers: {
                    "X-Keel-Staleness-Seconds": components["headers"]["Staleness"];
                    "X-Keel-Methodology-Version": components["headers"]["MethodologyVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetListResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    getAssetDepth: {
        parameters: {
            query?: {
                /**
                 * @description The quote asset used as the unit of measurement. If omitted, the asset's
                 *     PRIMARY pair is used, and the primary pair is always
                 *     USDC:GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN. That is
                 *     `docs/methodology/02-pair-selection.md` section 2, and it follows from
                 *     section 1: the candidate quote set is exactly USDC and native XLM, and
                 *     every threshold is a USDC figure.
                 *
                 *     It is a fixed identity and not a measurement, so the pair this resolves to
                 *     does not change when depth changes. Until contract 1.5.1 this parameter
                 *     described the primary pair as the one with the largest combined depth at
                 *     10 percent; no such rule was ever adopted and DEC-015 replaced it.
                 *
                 *     An asset measured against several quotes with no USDC pair among them
                 *     cannot resolve without this parameter and answers 400 INVALID_ASSET_ID
                 *     listing its `quoteCandidates` and the `primaryQuote` it was looking for.
                 * @example XLM
                 */
                quote?: components["parameters"]["Quote"];
                /**
                 * @description The ledger sequence for a historical replay. When set, `dataSource` in the
                 *     response will be `hubble`.
                 * @example 60912345
                 */
                ledger?: components["parameters"]["Ledger"];
            };
            header?: never;
            path: {
                /**
                 * @description The asset identity. The format is `CODE:ISSUER` for an issued asset, or
                 *     `XLM` for the native asset. The colon does not need encoding, but a
                 *     consumer using a strict URL builder may encode it as `%3A`.
                 */
                assetId: components["parameters"]["AssetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description The risk metrics. Note that an asset with no executable price also
             *     returns 200, with `priceSource: "none"` and band `CRITICAL`.
             */
            200: {
                headers: {
                    "X-Keel-Staleness-Seconds": components["headers"]["Staleness"];
                    "X-Keel-Methodology-Version": components["headers"]["MethodologyVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetRisk"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["HistoricalUnavailable"];
        };
    };
    getAssetHistory: {
        parameters: {
            query?: {
                /**
                 * @description The quote asset used as the unit of measurement. If omitted, the asset's
                 *     PRIMARY pair is used, and the primary pair is always
                 *     USDC:GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN. That is
                 *     `docs/methodology/02-pair-selection.md` section 2, and it follows from
                 *     section 1: the candidate quote set is exactly USDC and native XLM, and
                 *     every threshold is a USDC figure.
                 *
                 *     It is a fixed identity and not a measurement, so the pair this resolves to
                 *     does not change when depth changes. Until contract 1.5.1 this parameter
                 *     described the primary pair as the one with the largest combined depth at
                 *     10 percent; no such rule was ever adopted and DEC-015 replaced it.
                 *
                 *     An asset measured against several quotes with no USDC pair among them
                 *     cannot resolve without this parameter and answers 400 INVALID_ASSET_ID
                 *     listing its `quoteCandidates` and the `primaryQuote` it was looking for.
                 * @example XLM
                 */
                quote?: components["parameters"]["Quote"];
                /**
                 * @description The starting ledger sequence, inclusive. Required WITH `to`, or omit
                 *     both for the most recent stored readings of this source.
                 * @example 60890000
                 */
                from?: number;
                /**
                 * @description The ending ledger sequence, inclusive. Required WITH `from`, or omit
                 *     both for the most recent stored readings of this source.
                 * @example 60950000
                 */
                to?: number;
                /**
                 * @description The most rows one response may carry. Without a window this bounds
                 *     how far back the stored readings are taken from, newest first, and
                 *     they are still returned oldest first.
                 */
                limit?: number;
                /**
                 * @description The aggregation interval between data points. Applied only to a
                 *     windowed request: without a window there is no range to divide into
                 *     buckets, and bucketing anyway would collapse the three stored
                 *     February reconstructions, which close inside one hour and read from
                 *     LOW to CRITICAL, into a single point.
                 */
                resolution?: "hour" | "day";
                /**
                 * @description Which data source the series is drawn from. One source per response,
                 *     never a mixture. `horizon` and `hubble` are direct readings;
                 *     `offers-implied` is reconstructed from posted offers and the trades
                 *     that consumed them, and `trades-implied` from executed trades alone,
                 *     which makes the last one a lower bound rather than a measurement. The
                 *     DataSource schema carries what the `offers-implied` fold cannot see by
                 *     itself. A value outside this set is 400 INVALID_RANGE and not an empty
                 *     series, because "no data" and "no such source" are different answers.
                 */
                source?: "horizon" | "hubble" | "offers-implied" | "trades-implied";
            };
            header?: never;
            path: {
                /**
                 * @description The asset identity. The format is `CODE:ISSUER` for an issued asset, or
                 *     `XLM` for the native asset. The colon does not need encoding, but a
                 *     consumer using a strict URL builder may encode it as `%3A`.
                 */
                assetId: components["parameters"]["AssetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The time series */
            200: {
                headers: {
                    "X-Keel-Methodology-Version": components["headers"]["MethodologyVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["HistoricalUnavailable"];
        };
    };
}
